// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0LczjhRU_9r689lf-MltoHXKtN_H9MAE',
    appId: '1:457368784032:web:6c476bb3bcfbee58d44dc5',
    messagingSenderId: '457368784032',
    projectId: 'mobile-learning-8aa02',
    authDomain: 'mobile-learning-8aa02.firebaseapp.com',
    storageBucket: 'mobile-learning-8aa02.firebasestorage.app',
    measurementId: 'G-3CJG84B6WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVSbi2QhjuFKUWFsghOgkQSOGLPYhIqK4',
    appId: '1:457368784032:android:d5efea9107f4a5b3d44dc5',
    messagingSenderId: '457368784032',
    projectId: 'mobile-learning-8aa02',
    storageBucket: 'mobile-learning-8aa02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkORQaR8XFsGXqemJX3jhSbBC7DTdROx4',
    appId: '1:457368784032:ios:6edf71495e40c227d44dc5',
    messagingSenderId: '457368784032',
    projectId: 'mobile-learning-8aa02',
    storageBucket: 'mobile-learning-8aa02.firebasestorage.app',
    iosBundleId: 'com.example.udooErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkORQaR8XFsGXqemJX3jhSbBC7DTdROx4',
    appId: '1:457368784032:ios:6edf71495e40c227d44dc5',
    messagingSenderId: '457368784032',
    projectId: 'mobile-learning-8aa02',
    storageBucket: 'mobile-learning-8aa02.firebasestorage.app',
    iosBundleId: 'com.example.udooErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0LczjhRU_9r689lf-MltoHXKtN_H9MAE',
    appId: '1:457368784032:web:92e7bebb42cd0c9cd44dc5',
    messagingSenderId: '457368784032',
    projectId: 'mobile-learning-8aa02',
    authDomain: 'mobile-learning-8aa02.firebaseapp.com',
    storageBucket: 'mobile-learning-8aa02.firebasestorage.app',
    measurementId: 'G-9YN8BXX6LT',
  );
}
